// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsDbg
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsDbg.875ccb25-6b86-4dc8-86fc-73ec714e2818";
        public const string Name = "VsDbg";
        public const string Description = @"Misc commands for dbg (dubeg)";
        public const string Language = "en-US";
        public const string Version = "1.7";
        public const string Author = "DUBEG";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
