// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsDbg
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VsDbgString = "bbda3f82-23d0-4ed9-8244-3701c4042139";
        public static Guid VsDbg = new Guid(VsDbgString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainCmdGroup = 0x0001;
        public const int ToggleJSDebugging = 0x0100;
        public const int ToggleJustMyCode = 0x0200;
        public const int ToggleXamlHotReload = 0x0300;
        public const int ToggleCodeLens = 0x0400;
        public const int ToggleCSharpFadeOut = 0x0500;
        public const int ToggleCSharpInlineParameterNameHint = 0x0600;
        public const int ToggleAspnetIntegratedTerminal = 0x0700;
        public const int RefactorRename = 0x0800;
    }
}
